### ISSUE TITLE
Compat Validation Popup UI Issue with Firefox

### ISSUE THREAD

**Issue by ethanchewy** [github/auto-check-element#56]
As discovered in https://github.com/github/c2c-actions-service/issues/2787,  `auto-check` validation popup doesn't work as expected for Firefox. Only in Firefox the popup window does not "stick" with the input field and basically stays in the same fixed position after scrolling. It works fine in Chrome.

We can see this through our simple examples: https://github.github.com/auto-check-element/examples/

Chrome:

https://user-images.githubusercontent.com/8660827/155404915-39b32537-f166-4f8c-97c7-33002551427c.mov

Firefox:

https://user-images.githubusercontent.com/8660827/155405457-01f492d4-5478-4edd-8cde-d35b3b6d8714.mov

**Comment by koddsson** [comment]
The default behaviour for `<auto-check>` is to use HTML Form Validation and it looks like Firefox has a bug that has been open for a long time: https://bugzilla.mozilla.org/show_bug.cgi?id=1210025.

In dotcom we add event listeners to each element and show custom messages instead of the form validation ones.

https://github.com/github/github/blob/master/app/assets/modules/github/behaviors/autocheck.ts

You can see those form validation messages in action on https://github.com/new when you type in a repository name.

**Comment by gozer25** [comment]
[]() ok

**Comment by gozer25** [comment]
Ok
